<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>ff012e3b-43ee-4307-ac6c-9636db2f490a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0.cCFRUy.lsq-marvin-app-lg-button.lsq-marvin-app-primary-button.lsq-marvin-app-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af3b6527-0b1f-492d-9d96-6d3ef083d2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f829661-652e-4edd-8a7b-f76070b49777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-lg-button lsq-marvin-app-primary-button  lsq-marvin-app-button</value>
      <webElementGuid>689ef6a2-fffa-494b-a046-19103e532511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lsq-form-field-button-test</value>
      <webElementGuid>f1c08b38-b0e1-4703-987d-b903a1dc58ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>86d4e1d4-a51a-44a1-bb65-dfb898168a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>9925f140-9a80-4e2e-8717-328dd96ed150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fEOsli jFOxvN lsq-marvin-authentication-app&quot;]/div[@class=&quot;Layoutstyle__StyledContainer-lsq-marvin-auth-app__sc-qbpqeo-0 jWfNa-d container-fluid&quot;]/div[@class=&quot;Layoutstyle__StyledRow-lsq-marvin-auth-app__sc-qbpqeo-1 fJHaLh row-1 row&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-8 col-12&quot;]/div[@class=&quot;Cardstyle__StyledCard-lsq-marvin-auth-app__sc-16dovpd-0 hcZfKW&quot;]/button[@class=&quot;LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-lg-button lsq-marvin-app-primary-button  lsq-marvin-app-button&quot;]</value>
      <webElementGuid>dd073cab-88b2-47a8-b357-2006206a7df2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>ed80eea5-7d18-4def-b56d-2760fc1ae754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/button</value>
      <webElementGuid>3ddbc0eb-4a4f-4801-9f41-b1407a70fe1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::button[1]</value>
      <webElementGuid>359b369e-3b02-4cda-a1b2-d594c0a30703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>6a48ae30-f455-4aec-8232-5d8e6217c84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9a2b01f4-ad34-475d-af68-7444327c17e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Continue' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>6410954c-fc34-409f-ae07-25b51b2ce977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
