<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>13141739-40d2-442e-9352-50b432c8a114</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0.cCFRUy.lsq-marvin-app-lg-button.lsq-marvin-app-primary-button.lsq-marvin-app-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9493503-ad8e-4865-af94-27c1bdabfeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d76b62b8-c5b6-4a2e-978a-4faa8a530c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-lg-button lsq-marvin-app-primary-button  lsq-marvin-app-button</value>
      <webElementGuid>c8ba5c71-9516-44dd-ac84-068f7214a770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lsq-form-field-button-test</value>
      <webElementGuid>82e11188-8bea-4b19-adfb-1ad8a14a3708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>e9f09f37-9ad5-4c06-adfa-821df6724407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>cb055d9a-650d-40c1-b25d-8b7fbbf29747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fEOsli jFOxvN lsq-marvin-authentication-app&quot;]/div[@class=&quot;Layoutstyle__StyledContainer-lsq-marvin-auth-app__sc-qbpqeo-0 jWfNa-d container-fluid&quot;]/div[@class=&quot;Layoutstyle__StyledRow-lsq-marvin-auth-app__sc-qbpqeo-1 fJHaLh row-1 row&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-8 col-12&quot;]/div[@class=&quot;Cardstyle__StyledCard-lsq-marvin-auth-app__sc-16dovpd-0 hcZfKW&quot;]/button[@class=&quot;LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-lg-button lsq-marvin-app-primary-button  lsq-marvin-app-button&quot;]</value>
      <webElementGuid>b8fd0af8-f3ac-4abf-b9ca-e95f8f2fbfa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>fe439ca8-e4af-4a36-ada6-a0d53df19f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/button</value>
      <webElementGuid>f9f56dca-6d78-4362-bb11-1931c016130a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::button[1]</value>
      <webElementGuid>8327ca02-00a0-4141-8162-a39c9a56ed4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>8d8875e0-87ae-4201-9f1b-7ab2ca8c2103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7f943e6e-24f3-43ff-ab4b-8f5b68a81add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Continue' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>7f8db11a-4c9f-4ce0-9593-b96776cc1d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
