<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This Email Address does not exist in the system.Close notification</name>
   <tag></tag>
   <elementGuidId>6db75af8-3506-4f82-968d-5b42d5ec8793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification-1655570743927']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notification-1655570743927</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c39315c9-3828-4390-9b65-4e25f277fc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>0281089b-168f-4522-b0b3-65429515dd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledNotification-lsq-marvin-notification-comp__sc-1gt8ygv-0 gwjGZd position-top-center marvin-notification</value>
      <webElementGuid>6363ac7b-d135-428d-b68c-59e46951583f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notification-1655570743927</value>
      <webElementGuid>e1f9003e-ed68-406d-9a40-24281655b1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>f67329da-7a82-44b6-b353-a7a2ae1e31cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>notification-test</value>
      <webElementGuid>0e19a9c1-8b8e-4ddf-bd13-d8bd132a4d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This Email Address does not exist in the system.Close notification</value>
      <webElementGuid>4a6f576d-2a7c-4811-9db9-b94cb30b4b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification-1655570743927&quot;)</value>
      <webElementGuid>b784361e-cc4e-4df4-b837-94bb4a34d44d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notification-1655570743927']</value>
      <webElementGuid>2ba28a35-27fc-4ff3-b647-0961923a231a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]</value>
      <webElementGuid>2b13d79a-3b0c-496b-99ef-d48cc9257ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[2]</value>
      <webElementGuid>e582107c-799f-4f37-8c2f-eb12d11bd622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>0c5615e9-4f3a-4330-a0d5-ec00ebbe51d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'error' and @id = 'notification-1655570743927' and (text() = 'This Email Address does not exist in the system.Close notification' or . = 'This Email Address does not exist in the system.Close notification')]</value>
      <webElementGuid>c53f9891-e9e3-4e75-8d96-50621d7cbbff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
