<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>13a0a49b-2b4c-4896-9333-d2b785de3a83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0.cCFRUy.lsq-marvin-app-lg-button.lsq-marvin-app-primary-button.lsq-marvin-app-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a02637b2-aff0-4751-a3c9-5e6d8be79e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6787a4c-9db1-4827-b10b-0f2167ee7611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-lg-button lsq-marvin-app-primary-button  lsq-marvin-app-button</value>
      <webElementGuid>93dbb363-b264-46b6-a2d3-5b1bb2cb7a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lsq-form-field-button-test</value>
      <webElementGuid>ab42f93c-4b6e-4463-b43c-3808b028c8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>d86d2bce-1367-4750-aebf-c1ffcdef1187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>0f7b56b7-a8a5-4b37-96d9-430e94b5ee98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fEOsli jFOxvN lsq-marvin-authentication-app&quot;]/div[@class=&quot;Layoutstyle__StyledContainer-lsq-marvin-auth-app__sc-qbpqeo-0 jWfNa-d container-fluid&quot;]/div[@class=&quot;Layoutstyle__StyledRow-lsq-marvin-auth-app__sc-qbpqeo-1 fJHaLh row-1 row&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-8 col-12&quot;]/div[@class=&quot;Cardstyle__StyledCard-lsq-marvin-auth-app__sc-16dovpd-0 hcZfKW&quot;]/button[@class=&quot;LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-lg-button lsq-marvin-app-primary-button  lsq-marvin-app-button&quot;]</value>
      <webElementGuid>20329a15-4561-40ff-bbe9-f355d796e942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>8a7dfcbc-203e-4246-9966-a1e748091dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/button</value>
      <webElementGuid>5218f78a-5eb5-4e36-854e-f283f4ed13fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::button[1]</value>
      <webElementGuid>ebdd5cc8-62cf-4d09-99bb-62cd4dad369f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>ef49fcdd-d27b-48f6-b6e1-135a62f7e679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3c0834f6-5ca2-4221-b1f6-39d22091059f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Continue' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>d9e12b01-e941-4f92-afb2-1159d0a0d8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
