<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>69d7ada2-d9b2-4e1f-98b3-99ca11320d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0.cCFRUy.lsq-marvin-app-lg-button.lsq-marvin-app-primary-button.lsq-marvin-app-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7ac1efd-01d2-4442-b7a2-b6beeebc116f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3cfdc993-93ca-4419-ae59-41a278cfbc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-lg-button lsq-marvin-app-primary-button  lsq-marvin-app-button</value>
      <webElementGuid>46d22f58-0f36-4791-9b5f-3e72099ce406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lsq-form-field-button-test</value>
      <webElementGuid>c6fc1a5b-6e1d-45ed-84d4-459314a98c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>198c0c4f-3a13-4d68-985c-d3b81f949dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>96fed496-8b4e-40da-84b4-817b839e7dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fEOsli jFOxvN lsq-marvin-authentication-app&quot;]/div[@class=&quot;Layoutstyle__StyledContainer-lsq-marvin-auth-app__sc-qbpqeo-0 jWfNa-d container-fluid&quot;]/div[@class=&quot;Layoutstyle__StyledRow-lsq-marvin-auth-app__sc-qbpqeo-1 fJHaLh row-1 row&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-8 col-12&quot;]/div[@class=&quot;Cardstyle__StyledCard-lsq-marvin-auth-app__sc-16dovpd-0 hcZfKW&quot;]/button[@class=&quot;LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-lg-button lsq-marvin-app-primary-button  lsq-marvin-app-button&quot;]</value>
      <webElementGuid>81f51be6-8bea-4cc3-aa43-598b39cbee23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>e61857cb-9c19-473a-8e21-ab52b6a89045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/button</value>
      <webElementGuid>db39369c-3d2b-4927-b8cb-e0324f22a49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::button[1]</value>
      <webElementGuid>2dc3de8c-da5a-4fb3-83b5-31e8de4189fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>e96fd378-c36a-49f9-8e88-fd324aa73782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>73ecfdb5-252d-4393-92e4-d72ad74d7891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Continue' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>2779579d-dfc0-4655-8792-3ac0d1296a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
