<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check-In</name>
   <tag></tag>
   <elementGuidId>61a8ac34-aafc-4db7-a57a-28cb8b0cec08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CheckInButton-lsq-marvin-header-app__sc-xmo94y-13.jkaYYQ > button.LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0.cCFRUy.lsq-marvin-app-default-button.lsq-marvin-app-primary-button.lsq-marvin-app-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b92fb443-192f-4e68-a972-4058b154cf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80615c15-3e7e-436a-ad9d-4b1090723e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-default-button lsq-marvin-app-primary-button  lsq-marvin-app-button</value>
      <webElementGuid>24d1919d-c8db-44a8-b226-e783184c1cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lsq-form-field-button-test</value>
      <webElementGuid>038d7e5d-3766-4fde-a703-cef4e606c514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check-In</value>
      <webElementGuid>c57da328-8da0-445d-8f18-a09dd04a7ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lsq-marvin-base-modal-container&quot;)/div[@class=&quot;modal-content lsq-marvin-modal-content&quot;]/div[@class=&quot;LSQMarvinBodyContainer-lsq-marvin-modal-comp__sc-oz7t1u-0 ieJkQH lsq-marvin-modal-body StyledModalBody-lsq-marvin-header-app__sc-xmo94y-9 irwXNl&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;CheckInDiv-lsq-marvin-header-app__sc-xmo94y-10 dBWwwL&quot;]/div[@class=&quot;CheckInButton-lsq-marvin-header-app__sc-xmo94y-13 jkaYYQ&quot;]/button[@class=&quot;LSQMarvinButtonstyle__StyledButton-lsq-marvin-input-component__sc-1d7yadx-0 cCFRUy lsq-marvin-app-default-button lsq-marvin-app-primary-button  lsq-marvin-app-button&quot;]</value>
      <webElementGuid>e276e575-e155-4268-88bf-f75ca97f66a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>c55a1c75-3dfe-46aa-8868-2c27275ea740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lsq-marvin-base-modal-container']/div/div/div/div/div[3]/button</value>
      <webElementGuid>44971436-eed1-4782-a9fa-101b6ec03f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::button[1]</value>
      <webElementGuid>7b0d846f-5f85-4185-ae25-4d101637c0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 0 pages'])[1]/following::button[1]</value>
      <webElementGuid>6ee67d3b-e9ff-4bb4-91a1-d0132762e457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div[3]/button</value>
      <webElementGuid>fa989509-0ff4-42d0-87e1-138e66441a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Check-In' or . = 'Check-In')]</value>
      <webElementGuid>fde9b7d6-dca8-42ab-9dba-c898e3ad0443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
