<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This Email Address does not exist in th_a501c9</name>
   <tag></tag>
   <elementGuidId>c121e421-e652-4dd0-a01d-28d31f382e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification-1655570661747']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notification-1655570661747</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f88647d-5c17-4bcf-a5c3-641cf948dbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>37488d7f-2143-4f6c-b78e-563da1a60285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledNotification-lsq-marvin-notification-comp__sc-1gt8ygv-0 gwjGZd position-top-center marvin-notification</value>
      <webElementGuid>f5b934a0-e692-4e85-8b25-40aeca67e371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notification-1655570661747</value>
      <webElementGuid>2baf6c76-81cb-46f9-b302-5d34dff06350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>d14acef6-ec43-4020-aa24-b2f1be1e2cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>notification-test</value>
      <webElementGuid>74d87395-7407-4d2d-81e0-b6892e896faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This Email Address does not exist in the system.Close notification</value>
      <webElementGuid>90d11b94-5d63-4518-94af-ac024ad1fee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification-1655570661747&quot;)</value>
      <webElementGuid>b1219b20-08bb-46e4-b10e-93c65b0597dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notification-1655570661747']</value>
      <webElementGuid>b52078e2-f9a4-4a5a-8716-52b6c6dcfb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]</value>
      <webElementGuid>754daef3-2118-4726-bda0-a046a9538c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'notification-1655570661747', '&quot;', ')')])[1]/preceding::div[2]</value>
      <webElementGuid>6a9b7837-3ac5-4101-8df7-2327a76a70b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>f142211b-3bb1-494f-8b47-1d0e639e6b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'error' and @id = 'notification-1655570661747' and (text() = 'This Email Address does not exist in the system.Close notification' or . = 'This Email Address does not exist in the system.Close notification')]</value>
      <webElementGuid>1e9baa97-2a8d-4d68-b1a3-325c687b8f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
