<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_S</name>
   <tag></tag>
   <elementGuidId>9dfd93d9-8e6b-48c6-87a3-6858ec698d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.StyledProfilePicture-lsq-marvin-data-display-comp__sc-jjjequ-2.bONuSH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7269e848-6daa-4abd-8755-f1937320ab74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lsq-marvin-profile</value>
      <webElementGuid>26c55d25-f266-418f-a005-46cc7ae9c975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>rgb(var(--marvin-warning-1))</value>
      <webElementGuid>d983f111-6ca7-402d-9969-004692d4f630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledProfilePicture-lsq-marvin-data-display-comp__sc-jjjequ-2 bONuSH</value>
      <webElementGuid>2d70b74b-4a27-4364-b1ff-ad3fc2d8d531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>8056a6e9-fb88-4b95-b1b0-b065fc449c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-kgflAQ bnGynO lsq-marvin-home-app&quot;]/div[@class=&quot;StyledHomeContainer-lsq-marvin-home-app__sc-ave115-0 jdIKHg lsq-marvin-home-container&quot;]/div[@class=&quot;LSQMarvinHeaderContainer-lsq-marvin-home-app__sc-1q8cpul-0 czeoju lsq-marvin-header-app&quot;]/div[@class=&quot;MainLeftHeader-lsq-marvin-header-app__sc-1oa1rgk-1 eQnWcB shimmer-hidden&quot;]/div[@class=&quot;MenuContainer-lsq-marvin-header-app__sc-1oa1rgk-2 fPqIHh&quot;]/div[@class=&quot;MenuItem-lsq-marvin-header-app__sc-1oa1rgk-3 chEGxc lsq-marvin-profile-component lsq-marvin-menu-list&quot;]/div[@class=&quot;ProfileContainer-lsq-marvin-data-display-comp__sc-jjjequ-0 dgvQBa lsq-marvin-profile-picture-container&quot;]/div[@class=&quot;StyledWrapper-lsq-marvin-data-display-comp__sc-jjjequ-1 gfWikb StyledProfilePicture-lsq-marvin-header-app__sc-1oa1rgk-8 facIYk lsq-marvin-profile-picture lsq-marvin-profile-picture-wrapper&quot;]/div[@class=&quot;StyledProfilePicture-lsq-marvin-data-display-comp__sc-jjjequ-2 bONuSH&quot;]</value>
      <webElementGuid>4d3dba79-c2d8-4e50-a9b4-4796b0b216c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div[2]/div/div/div</value>
      <webElementGuid>04e5ffa0-23e3-4366-ac98-bcf32df61d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart Views'])[1]/preceding::div[5]</value>
      <webElementGuid>b300b198-ed0d-4302-b32a-50200e381f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div</value>
      <webElementGuid>10b56ad3-1059-4562-9228-d11ac1ffbd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'S' or . = 'S')]</value>
      <webElementGuid>46b95f69-9731-48b5-974d-14825ed1d5f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
