<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_LSQEmail</name>
   <tag></tag>
   <elementGuidId>7748a155-8679-4618-87f0-715d3da42e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LSQEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LSQEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f7bc846-85b1-4329-8865-08edf40e2cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c6b8504-b362-40fc-9495-6f7268507b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LSQEmail</value>
      <webElementGuid>9fb57b88-41d8-4df3-ad22-1cd966d25c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LSQEmail</value>
      <webElementGuid>7a9ad43b-5a19-403d-8320-1055e828f633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f06a20f0-b5ce-435b-8d5b-d3072bd35147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fde053d8-76b9-4369-8dc9-e97b984556b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>01ed8065-30b0-4f32-b756-842d664807c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LSQMarvinInputstyle__StyledInput-lsq-marvin-input-component__sc-n56uul-0 kfOpJC lsq-marvin-app-lg-input  false lsq-marvin-app-input  </value>
      <webElementGuid>d058435c-084b-416f-8841-229a6df18413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lsq-form-field-input-test</value>
      <webElementGuid>aaced41e-80f1-4d67-a9b6-8c90e9e22da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>ca3e6aad-b802-4a32-ab2d-6356c623103e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02c01305-c18c-405b-8a16-aa6c569ef28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>02621b15-5eb5-466d-ab73-bc8f397d5269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>lsq-email</value>
      <webElementGuid>20bc3db2-1dbf-47ec-b46d-06f4e7fb6b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LSQEmail&quot;)</value>
      <webElementGuid>a4507c68-ea10-449f-856e-84c89ba02756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LSQEmail']</value>
      <webElementGuid>a051dc70-865e-4675-ae69-00a814c71877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>7ee5ca1e-fc8d-4094-b00a-bb4f0847418c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8dd301a4-c105-4ccb-add4-eb6145019240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LSQEmail' and @name = 'LSQEmail' and @placeholder = 'Email Address']</value>
      <webElementGuid>bb7165cb-1052-47ba-9e51-ba9c75c6cd21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
