<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This Email Address does not exist in the system.Close notification</name>
   <tag></tag>
   <elementGuidId>458250aa-545a-41d6-ae31-f226043ecda3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification-1655538304497']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notification-1655538304497</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ff2fc5f-3522-40d6-9ae6-76c4b0aa77e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>1e4786f0-ba2c-460b-a2aa-0d3cb931c67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledNotification-lsq-marvin-notification-comp__sc-1gt8ygv-0 gwjGZd position-top-center marvin-notification</value>
      <webElementGuid>178271fe-5028-45b7-b8ad-84a96ea9f685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notification-1655538304497</value>
      <webElementGuid>fd2ff989-d447-4220-86c0-657fe66b270c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>854fc096-a94f-4fbb-b23f-464c48825127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>notification-test</value>
      <webElementGuid>d5edbd19-1e99-4b21-b138-34d74d681910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This Email Address does not exist in the system.Close notification</value>
      <webElementGuid>b74bf4fb-cffd-4a46-b3e8-75031ff86521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification-1655538304497&quot;)</value>
      <webElementGuid>9d7f7324-d854-40a0-802f-bc5b6b40ed7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notification-1655538304497']</value>
      <webElementGuid>19b5601d-1fac-4858-aeaf-bcf56a3eb180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]</value>
      <webElementGuid>44b35b2e-f547-45b0-91c0-58d6b3772f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[2]</value>
      <webElementGuid>3847b488-2365-4a68-85b3-c98eb825da83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>32a0b273-1538-4dec-9c9c-4226453e913f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'error' and @id = 'notification-1655538304497' and (text() = 'This Email Address does not exist in the system.Close notification' or . = 'This Email Address does not exist in the system.Close notification')]</value>
      <webElementGuid>d91d46b8-d5fb-47df-a9b9-be4833d9ec1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
