<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test</name>
   <tag></tag>
   <elementGuidId>6cfcd90a-10fd-447b-bf05-57ba652c2d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;TestForm('0f2d923a-5475-40a3-b290-b52a441a083b', false);&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e156bc2-49ca-4959-a0ed-c0ddc6918b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small-x</value>
      <webElementGuid>cad6ae73-4559-4dfd-b299-fa617541f3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>401cea2c-bdb6-4d6f-9099-9ecbff37a36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TestForm('0f2d923a-5475-40a3-b290-b52a441a083b', false);</value>
      <webElementGuid>8a8713d3-1a1a-4326-89cf-335ab0ca9093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>521d67d0-6caf-4a39-b2f0-837f7dee9ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormGrid&quot;)/table[1]/tbody[1]/tr[@class=&quot;hoverBackground&quot;]/td[@class=&quot;t-last&quot;]/div[@class=&quot;settings-actions btn-group button-positioning open&quot;]/ul[@class=&quot;dropdown-menu ul-setting&quot;]/li[6]/a[@class=&quot;small-x&quot;]</value>
      <webElementGuid>ed3dfc66-5234-449f-a4e4-a2464b9cf6b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;TestForm('0f2d923a-5475-40a3-b290-b52a441a083b', false);&quot;]</value>
      <webElementGuid>e5a9bf74-7a11-4dd1-8626-c3948caf63e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormGrid']/table/tbody/tr/td[7]/div/ul/li[6]/a</value>
      <webElementGuid>a89941c8-2d08-4828-aa92-5847b3d6d53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Test')]</value>
      <webElementGuid>3d838564-00a5-4311-9396-0a036cca49dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unpublish'])[1]/following::a[1]</value>
      <webElementGuid>5071bc82-5133-44bb-8611-30c59ced6556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename'])[1]/following::a[2]</value>
      <webElementGuid>7a579171-b0c9-418e-8b75-001333a5f015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Form HTML'])[1]/preceding::a[1]</value>
      <webElementGuid>089e51e1-8216-4dff-9ac6-76f2fe023ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Edit'])[1]/preceding::a[2]</value>
      <webElementGuid>0b8ae4dd-14c8-4777-9c4c-623e43582304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test']/parent::*</value>
      <webElementGuid>7f550425-7563-4d66-b52a-77fa4811a906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[11]</value>
      <webElementGuid>4c5e767c-574b-4a24-8178-d4124599125c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/ul/li[6]/a</value>
      <webElementGuid>07b35b96-8efc-4a72-9a2f-847d8b0d3e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Test' or . = 'Test')]</value>
      <webElementGuid>a5203546-3171-4c39-a3b8-93cefbb679e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
