<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your login details_EmailID</name>
   <tag></tag>
   <elementGuidId>8fe540e6-7125-41e2-8235-23eba3291deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EmailID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc64f33c-94b3-4516-8b7a-887fa7ec3f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>d624c995-ceeb-474b-84f9-dce995388627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>887036d8-8449-4979-856c-726dc3ccdcbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Enter a valid email address</value>
      <webElementGuid>f99156d7-b880-4f2d-91a4-1ffd8cc900be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\s*((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.+]?[a-zA-Z0-9])*))[@]((([a-zA-Z0-9])+)|([a-zA-Z0-9]+([_\-\.]?[a-zA-Z0-9])*))[\.][a-zA-Z]{2,}\s*$</value>
      <webElementGuid>8998a2c8-c327-433a-ab18-b950ead18cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Email address is required</value>
      <webElementGuid>fdd12626-bcdd-4d0c-8af4-cb4f5c1005dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>31d49c43-d071-4d24-a228-ed659a3154ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>04af5790-93a4-4901-841d-940773e51b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailID</value>
      <webElementGuid>45f3362f-e87a-472f-9dc6-8d872c7031df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>f31c1a09-e72f-4e1b-aba6-c8e9c730eeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>192025a4-b8fa-44b7-9be7-938e6ff572d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailID&quot;)</value>
      <webElementGuid>0f187819-3f42-4d9b-b2da-67978923bc60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailID']</value>
      <webElementGuid>28fae9d5-97fc-4a22-a8e4-5a7ca6ef75e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='VerifyEmailForm']/input</value>
      <webElementGuid>475166fa-ee01-40a2-9293-b77cdd00ca1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6a2dc5f8-681c-4bc6-ad2c-f6b0a4528a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailID' and @name = 'EmailID' and @placeholder = 'Email address' and @type = 'text']</value>
      <webElementGuid>2f624f29-51ce-42ed-91aa-ed35f8662ed1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
